# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '7.0'

target 'example', :exclusive => true do
    pod "TRCropViewController", :path => "../"
end


